---

root: true

plugins:
  - jest
  - functional
  - testing-library
  - jest-dom

env:
  jest: true
  browser: true
  es2020: true

parserOptions:
  ecmaVersion: 2020

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'
  - 'plugin:testing-library/recommended'
  - "plugin:jest-dom/recommended"

rules:
  import/extensions: 0
  import/no-unresolved: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-param-reassign: 0
